#version 1 has the basic functionality of compose
#version 2 lets the services communicate with each other using their names instead of relying on the links option to specify
#version 3 has support for docker swarm,has some functionality removed from previous versions

#version number must be specified before the commands are given(for version 2+)

version: "2"
services:
    redis:
        image: redis
    db:
        image: postgres:9.4
        networks:
            - back-end
    vote:
        image: voting-app
        #or
        build: ./vote # the file path for the image
        ports:
            - 5000:80 #host:container(server)
        links:
            - redis # unnecessary in version 2 of compose
        depends_on:
            - redis #used to tell compose that this cannot be run before redis is running
        networks:
            - front-end
            - back-end

    result:
        build: ./result
        ports:
            - 5001:80
        links:
            - db
        networks:
            - front-end
            - back-end

    worker:
        build: ./worker
        links:
            - db
            - redis
        networks:
            - back-end

networks:
    front-end:
    back-end:

